# Generated by Django 5.1.5 on 2025-01-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_subtask_task'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together={('task', 'name')},
        ),
    ]
